Repository StackStorm/ansible-st2, pull requests merged in 2018-10, with the labels that each got.

#209 Fix ansible-lint warnings about using Jinja expressions in 'when'
  roles/bwc/tasks/license.yml
Labels: RFR, enhancement

#208 Fix deprecated warnings with Ansible 2.7
  roles/bwc/tasks/bwc_repos_apt.yml
  roles/mongodb/tasks/mongodb_apt.yml
  roles/mongodb/tasks/mongodb_yum.yml
  roles/postgresql/tasks/postgresql_apt.yml
  roles/postgresql/tasks/postgresql_yum6.yml
  roles/postgresql/tasks/postgresql_yum7.yml
  roles/st2/tasks/auth.yml
  roles/st2repo/tasks/st2repo_apt.yml
Labels: enhancement

#211 Changed use of Jinja filters as tests
  roles/st2mistral/tasks/main.yml
Labels: deprecations, enhancement

#212 Add new service 'st2scheduler', implement st2-version dependent logic
  roles/st2/tasks/main.yml
  roles/st2/tasks/version.yml
  roles/st2/vars/main.yml
Labels: feature

#213 Use older 'version_compare' jinja test, compatible with Ansible before v2.5.0
  roles/st2/tasks/version.yml
Labels: enhancement

#214 Fix 'get installed st2 version' task not being run properly in some Ansible versions
  roles/st2/tasks/version.yml
Labels: bug
