Repository StackStorm/ansible-st2, pull requests merged in 2019-04, with the labels that each got.

#233 Fix an issue with st2api not being restarted after installing bwc-enterprise package, fix services which are restarted when configuring ldap backend in st2.conf
  roles/StackStorm.ewc/tasks/ldap.yml
  roles/StackStorm.ewc/tasks/main.yml
  roles/StackStorm.ewc/tasks/rbac.yml
  roles/StackStorm.ewc_smoketests/tasks/main.yml
  roles/StackStorm.st2/handlers/main.yml
Labels: bug

#235 Fix 'ewc_license' conditional check in stackstorm.yml example play
  stackstorm.yml
Labels: RFR, bug

#234 Ensure st2.conf values are not converted to particular structure
  roles/StackStorm.st2/tasks/config.yml
  roles/StackStorm.st2mistral/tasks/config.yml
Labels: RFR, enhancement

#239 st2chatops also may need proxies
  roles/StackStorm.st2/tasks/proxy.yml
Labels: bug

#236 Bring in proxy env vars if defined as Ansible vars
  stackstorm.yml
Labels: enhancement

#240 Move proxy settings for Chatops to respective `StackStorm.st2chatops` role
  roles/StackStorm.st2/tasks/proxy.yml
  roles/StackStorm.st2chatops/tasks/main.yml
  stackstorm.yml
Labels: enhancement
