Repository StackStorm/ansible-st2, pull requests merged in 2020-07, with the labels that each got.

#268 Remove EL6 from ansible playbooks
  .kitchen-docker/centos6/Dockerfile
  .kitchen.yml
  .travis.yml
  README.md
  Vagrantfile
  meta/main.yml
  roles/StackStorm.epel/meta/main.yml
  roles/StackStorm.ewc/meta/main.yml
  roles/StackStorm.ewc_smoketests/meta/main.yml
  roles/StackStorm.mongodb/meta/main.yml
  roles/StackStorm.nginx/meta/main.yml
  roles/StackStorm.nodejs/meta/main.yml
  roles/StackStorm.postgresql/meta/main.yml
  roles/StackStorm.postgresql/tasks/postgresql_yum6.yml
  roles/StackStorm.rabbitmq/meta/main.yml
  roles/StackStorm.rabbitmq/tasks/main.yml
  roles/StackStorm.rabbitmq/vars/main.yml
  roles/StackStorm.st2/meta/main.yml
  roles/StackStorm.st2/tasks/main.yml
  roles/StackStorm.st2chatops/meta/main.yml
  roles/StackStorm.st2mistral/meta/main.yml
  roles/StackStorm.st2repo/meta/main.yml
  roles/StackStorm.st2web/meta/main.yml
Labels: breaking change, enhancement, size/L

#269 Support for Ubuntu 18.04
  .kitchen.yml
  .travis.yml
  README.md
  Vagrantfile
  meta/main.yml
  roles/StackStorm.ewc/meta/main.yml
  roles/StackStorm.ewc_smoketests/meta/main.yml
  roles/StackStorm.mongodb/meta/main.yml
  roles/StackStorm.nginx/meta/main.yml
  roles/StackStorm.nodejs/meta/main.yml
  roles/StackStorm.rabbitmq/meta/main.yml
  roles/StackStorm.st2/meta/main.yml
  roles/StackStorm.st2chatops/meta/main.yml
  roles/StackStorm.st2repo/meta/main.yml
  roles/StackStorm.st2web/meta/main.yml
  stackstorm.yml
Labels: feature, size/M

#271 Add Github Sponsor button
  .github/FUNDING.yml
Labels: enhancement, size/XS

#272 Deprecation of mistral, remove mistral and postgresql roles
  README.md
  meta/main.yml
  roles/StackStorm.postgresql/meta/main.yml
  roles/StackStorm.postgresql/tasks/main.yml
  roles/StackStorm.postgresql/tasks/postgresql_apt.yml
  roles/StackStorm.postgresql/tasks/postgresql_yum7.yml
  roles/StackStorm.st2/vars/main.yml
  roles/StackStorm.st2mistral/defaults/main.yml
  roles/StackStorm.st2mistral/handlers/main.yml
  roles/StackStorm.st2mistral/meta/main.yml
  roles/StackStorm.st2mistral/tasks/config.yml
  roles/StackStorm.st2mistral/tasks/main.yml
  roles/StackStorm.st2mistral/templates/init_mistral_db.SQL.j2
  roles/StackStorm.st2mistral/vars/main.yml
  stackstorm.yml
Labels: breaking change, feature, size/L
